"""Paletted chunk storage and collision access for the physics engine."""

from __future__ import annotations

import gzip
import io
import json
import math
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .errors import ProtocolError
from .physics.geometry import AABB, Vec3
from .physics.math import f32
from .physics.world import (
    AIR,
    ALL_HORIZONTAL_FLOW_FACES,
    DEFAULT_BLOCK,
    FULL_BLOCK,
    BlockProperties,
    fluid_flow,
    fluid_height,
)
from .protocol.codec import PacketReader


@dataclass(frozen=True, slots=True)
class BlockStateDefinition:
    name: str
    shapes: tuple[AABB, ...]
    properties: BlockProperties = DEFAULT_BLOCK


class BlockStateRegistry:
    """Map numeric state IDs to collision and movement properties.

    State 0 is air. Until generated per-version shape tables are installed, unknown
    states use a conservative full cube. Call :meth:`register` to supply exact data.
    """

    def __init__(self) -> None:
        self._states: dict[int, BlockStateDefinition] = {
            0: BlockStateDefinition("minecraft:air", (), AIR)
        }
        self._unknown = BlockStateDefinition("protobot:unknown_full_block", (FULL_BLOCK,))

    def register(self, state_id: int, definition: BlockStateDefinition) -> None:
        if state_id < 0:
            raise ValueError("block state id cannot be negative")
        self._states[state_id] = definition

    def get(self, state_id: int) -> BlockStateDefinition:
        return self._states.get(state_id, self._unknown)

    @classmethod
    def from_report(cls, report: str | Path | Mapping[str, Any]) -> BlockStateRegistry:
        """Build a state registry from Mojang's ``reports/blocks.json``.

        The report is generated by the official server jar and is intentionally
        accepted as an input rather than bundled in the wheel.  This keeps the
        core package small while allowing each supported release (and modded
        server) to supply its own authoritative state IDs.
        """

        registry = cls()
        registry.load_report(report)
        return registry

    def load_report(self, report: str | Path | Mapping[str, Any]) -> int:
        """Register all states from a blocks report and return the count."""

        if isinstance(report, (str, Path)):
            with Path(report).open("r", encoding="utf-8") as stream:
                report = json.load(stream)
        if not isinstance(report, Mapping):
            raise TypeError("blocks report must be a mapping")
        registered = 0
        for name, block in report.items():
            if not isinstance(name, str) or not isinstance(block, Mapping):
                continue
            definition = block.get("definition")
            block_type = (
                definition.get("type", "minecraft:block")
                if isinstance(definition, Mapping)
                else "minecraft:block"
            )
            states = block.get("states", ())
            if not isinstance(states, list):
                continue
            for state in states:
                if not isinstance(state, Mapping) or not isinstance(state.get("id"), int):
                    continue
                properties = state.get("properties", {})
                if not isinstance(properties, Mapping):
                    properties = {}
                self.register(
                    state["id"],
                    self._definition_for(name, str(block_type), properties),
                )
                registered += 1
        return registered

    def load_table(self, table: str | Path | Mapping[str, Any]) -> int:
        """Load a compact table produced by :mod:`tools.export_block_states`."""

        if isinstance(table, (str, Path)):
            path = Path(table)
            if path.suffix == ".gz":
                with gzip.open(path, "rt", encoding="utf-8") as stream:
                    table = json.load(stream)
            else:
                with path.open("r", encoding="utf-8") as stream:
                    table = json.load(stream)
        if not isinstance(table, Mapping) or not isinstance(table.get("states"), Mapping):
            raise TypeError("block state table must contain a states mapping")
        count = 0
        for raw_id, raw_definition in table["states"].items():
            try:
                state_id = int(raw_id)
            except (TypeError, ValueError):
                continue
            if not isinstance(raw_definition, Mapping):
                continue
            raw_shapes = raw_definition.get("shapes", ())
            shapes: list[AABB] = []
            if isinstance(raw_shapes, list):
                for values in raw_shapes:
                    if isinstance(values, list) and len(values) == 6:
                        shapes.append(AABB(*(float(value) for value in values)))
            raw_properties = raw_definition.get("properties", {})
            if not isinstance(raw_properties, Mapping):
                raw_properties = {}
            # Tables generated by older ProtoBot releases predate the
            # scaffolding/bounce metadata fields.  Keep those tables useful
            # when they are loaded alongside the newer physics engine by
            # deriving vanilla name-based defaults when the field is absent.
            # The CLIMBABLE fallback below also repairs the legacy
            # scaffolding entry, which was serialized with a stale ``false``.
            name = str(raw_definition.get("name", "unknown"))
            inferred_climbable = name in {
                "minecraft:ladder",
                "minecraft:vine",
                "minecraft:scaffolding",
                "minecraft:weeping_vines",
                "minecraft:weeping_vines_plant",
                "minecraft:twisting_vines",
                "minecraft:twisting_vines_plant",
                "minecraft:cave_vines",
                "minecraft:cave_vines_plant",
            }
            inferred_scaffolding = name == "minecraft:scaffolding"
            inferred_bounce = 1.0 if "slime" in name else 0.0
            inferred_suppress_bounce = name in {
                "minecraft:honey_block",
            }
            inferred_powder_snow = name == "minecraft:powder_snow"
            inferred_boat_ignored_friction = name == "minecraft:lily_pad"
            inferred_stuck_multiplier = {
                "minecraft:cobweb": (0.25, f32(0.05), 0.25),
                "minecraft:sweet_berry_bush": (f32(0.8), 0.75, f32(0.8)),
            }.get(name)
            inferred_weaving_multiplier = (
                (0.5, 0.25, 0.5) if name == "minecraft:cobweb" else None
            )
            inferred_blocks_motion = bool(shapes) and name not in {
                "minecraft:cobweb",
                "minecraft:bamboo_sapling",
            }
            inferred_sturdy_faces = (
                ALL_HORIZONTAL_FLOW_FACES if tuple(shapes) == (FULL_BLOCK,) else 0
            )
            raw_flow = raw_properties.get("fluid_flow")
            if isinstance(raw_flow, (list, tuple)) and len(raw_flow) == 3:
                try:
                    fluid_flow = tuple(float(value) for value in raw_flow)
                except (TypeError, ValueError):
                    fluid_flow = None
            else:
                fluid_flow = None
            properties = BlockProperties(
                friction=float(raw_properties.get("friction", DEFAULT_BLOCK.friction)),
                speed_factor=float(raw_properties.get("speed_factor", 1.0)),
                jump_factor=float(raw_properties.get("jump_factor", 1.0)),
                # The first bundled table marked scaffolding as non-climbable
                # even though it belongs to vanilla's CLIMBABLE tag.  Keep
                # the name fallback for that legacy entry while honoring the
                # serialized value for all other blocks.
                climbable=bool(raw_properties.get("climbable", False) or inferred_climbable),
                scaffolding=bool(
                    raw_properties.get("scaffolding", inferred_scaffolding)
                ),
                fluid=raw_properties.get("fluid"),
                fluid_height=float(raw_properties.get("fluid_height", 0.0)),
                fluid_flow=fluid_flow,
                fluid_falling=bool(raw_properties.get("fluid_falling", False)),
                blocks_motion=bool(
                    raw_properties.get("blocks_motion", inferred_blocks_motion)
                ),
                fluid_sturdy_faces=int(
                    raw_properties.get("fluid_sturdy_faces", inferred_sturdy_faces)
                ),
                bounce_restitution=float(
                    raw_properties.get("bounce_restitution", inferred_bounce)
                ),
                suppress_bounce=bool(
                    raw_properties.get("suppress_bounce", inferred_suppress_bounce)
                ),
                bubble_column_drag_down=(
                    bool(raw_properties["bubble_column_drag_down"])
                    if raw_properties.get("bubble_column_drag_down") is not None
                    else None
                ),
                powder_snow=bool(
                    raw_properties.get("powder_snow", inferred_powder_snow)
                ),
                stuck_speed_multiplier=self._read_vec3_property(
                    raw_properties.get("stuck_speed_multiplier"),
                    inferred_stuck_multiplier,
                ),
                weaving_stuck_speed_multiplier=self._read_vec3_property(
                    raw_properties.get("weaving_stuck_speed_multiplier"),
                    inferred_weaving_multiplier,
                ),
                honey_block=bool(
                    raw_properties.get("honey_block", name == "minecraft:honey_block")
                ),
                slime_block=bool(
                    raw_properties.get("slime_block", name == "minecraft:slime_block")
                ),
                boat_ignored_friction=bool(
                    raw_properties.get(
                        "boat_ignored_friction",
                        inferred_boat_ignored_friction,
                    )
                ),
            )
            self.register(
                state_id,
                BlockStateDefinition(
                    name,
                    tuple(shapes),
                    properties,
                ),
            )
            count += 1
        return count

    @staticmethod
    def _read_vec3_property(
        value: object,
        default: tuple[float, float, float] | None,
    ) -> tuple[float, float, float] | None:
        if not isinstance(value, (list, tuple)) or len(value) != 3:
            return default
        try:
            x, y, z = (float(component) for component in value)
        except (TypeError, ValueError):
            return default
        if not all(math.isfinite(component) for component in (x, y, z)):
            return default
        return x, y, z

    def export_table(self, output: str | Path, *, version: str | None = None) -> int:
        """Write the current registry as a compact, portable JSON table."""

        states: dict[str, Any] = {}
        for state_id, definition in self._states.items():
            properties = definition.properties
            serialized_properties: dict[str, Any] = {
                "friction": properties.friction,
                "speed_factor": properties.speed_factor,
                "jump_factor": properties.jump_factor,
                "climbable": properties.climbable,
                "scaffolding": properties.scaffolding,
                "fluid": properties.fluid,
                "fluid_height": properties.fluid_height,
                "fluid_falling": properties.fluid_falling,
                "blocks_motion": properties.blocks_motion,
                "fluid_sturdy_faces": properties.fluid_sturdy_faces,
                "bounce_restitution": properties.bounce_restitution,
                "suppress_bounce": properties.suppress_bounce,
            }
            if properties.fluid_flow is not None:
                serialized_properties["fluid_flow"] = list(properties.fluid_flow)
            if properties.bubble_column_drag_down is not None:
                serialized_properties["bubble_column_drag_down"] = (
                    properties.bubble_column_drag_down
                )
            if properties.powder_snow:
                serialized_properties["powder_snow"] = True
            if properties.stuck_speed_multiplier is not None:
                serialized_properties["stuck_speed_multiplier"] = list(
                    properties.stuck_speed_multiplier
                )
            if properties.weaving_stuck_speed_multiplier is not None:
                serialized_properties["weaving_stuck_speed_multiplier"] = list(
                    properties.weaving_stuck_speed_multiplier
                )
            if properties.honey_block:
                serialized_properties["honey_block"] = True
            if properties.slime_block:
                serialized_properties["slime_block"] = True
            if properties.boat_ignored_friction:
                serialized_properties["boat_ignored_friction"] = True
            states[str(state_id)] = {
                "name": definition.name,
                "shapes": [
                    [shape.min_x, shape.min_y, shape.min_z, shape.max_x, shape.max_y, shape.max_z]
                    for shape in definition.shapes
                ],
                "properties": serialized_properties,
            }
        payload: dict[str, Any] = {"version": version, "states": states}
        path = Path(output)
        if path.suffix == ".gz":
            # A fixed gzip timestamp makes generated package data reproducible.
            with (
                path.open("wb") as raw_stream,
                gzip.GzipFile(
                    filename="",
                    mode="wb",
                    fileobj=raw_stream,
                    mtime=0,
                ) as compressed_stream,
                io.TextIOWrapper(compressed_stream, encoding="utf-8") as stream,
            ):
                json.dump(payload, stream, ensure_ascii=False, separators=(",", ":"))
        else:
            with path.open("w", encoding="utf-8") as stream:
                json.dump(payload, stream, ensure_ascii=False, separators=(",", ":"))
        return len(states)

    @staticmethod
    def _definition_for(
        name: str,
        block_type: str,
        properties: Mapping[str, Any],
    ) -> BlockStateDefinition:
        """Translate report metadata into useful collision primitives.

        Mojang's report intentionally omits voxel shapes.  The families below
        cover the shapes that matter most to locomotion and use a conservative
        full block for complex redstone/utility blocks.  A mod or application
        can replace any state with an exact :class:`BlockStateDefinition`.
        """

        air_types = {"minecraft:air", "minecraft:structure_void", "minecraft:end_portal"}
        if block_type in air_types or name in {
            "minecraft:air",
            "minecraft:cave_air",
            "minecraft:void_air",
        }:
            return BlockStateDefinition(name, (), AIR)

        fluid = None
        if block_type == "minecraft:liquid":
            fluid = "lava" if "lava" in name else "water"
            try:
                level = int(properties.get("level", 0))
            except (TypeError, ValueError):
                level = 0
            amount = 8 if level == 0 or level >= 8 else 8 - level
            fluid_height_value = f32(amount / 9.0)
            return BlockStateDefinition(
                name,
                (),
                BlockProperties(
                    fluid=fluid,
                    fluid_height=fluid_height_value,
                    fluid_falling=level >= 8,
                ),
            )
        if block_type == "minecraft:bubble_column":
            return BlockStateDefinition(
                name,
                (),
                BlockProperties(
                    fluid="water",
                    fluid_height=f32(8.0 / 9.0),
                    bubble_column_drag_down=(
                        str(properties.get("drag", "true")).lower() == "true"
                    ),
                ),
            )

        if name == "minecraft:powder_snow":
            return BlockStateDefinition(
                name,
                (),
                BlockProperties(powder_snow=True),
            )

        friction = f32(0.6)
        speed_factor = 1.0
        if "slime" in name:
            friction = f32(0.8)
        elif "ice" in name:
            friction = f32(0.98)
        elif "honey" in name or "soul_sand" in name or "soul_soil" in name:
            speed_factor = 0.4
        climbable = name in {"minecraft:ladder", "minecraft:vine", "minecraft:scaffolding"}
        scaffolding = name == "minecraft:scaffolding"
        waterlogged = str(properties.get("waterlogged", "false")) == "true"
        props = BlockProperties(
            friction=friction,
            speed_factor=speed_factor,
            climbable=climbable,
            scaffolding=scaffolding,
            fluid="water" if waterlogged else None,
            fluid_height=f32(8.0 / 9.0) if waterlogged else 0.0,
            blocks_motion=True,
            fluid_sturdy_faces=ALL_HORIZONTAL_FLOW_FACES,
            bounce_restitution=1.0 if "slime" in name else 0.0,
            stuck_speed_multiplier={
                "minecraft:cobweb": (0.25, f32(0.05), 0.25),
                "minecraft:sweet_berry_bush": (f32(0.8), 0.75, f32(0.8)),
            }.get(name),
            weaving_stuck_speed_multiplier=(
                (0.5, 0.25, 0.5) if name == "minecraft:cobweb" else None
            ),
            honey_block=name == "minecraft:honey_block",
            slime_block=name == "minecraft:slime_block",
            boat_ignored_friction=name == "minecraft:lily_pad",
        )

        full = (FULL_BLOCK,)
        if block_type in {
            "minecraft:carpet",
            "minecraft:wool_carpet",
            "minecraft:mossy_carpet",
        }:
            return BlockStateDefinition(name, (AABB(0.0, 0.0, 0.0, 1.0, 0.0625, 1.0),), props)
        if block_type == "minecraft:snow_layer":
            layers = max(1, min(8, int(properties.get("layers", 1))))
            return BlockStateDefinition(name, (AABB(0.0, 0.0, 0.0, 1.0, layers / 8.0, 1.0),), props)
        if block_type == "minecraft:slab":
            half = str(properties.get("type", "bottom"))
            if half == "double":
                shape = FULL_BLOCK
            elif half == "top":
                shape = AABB(0.0, 0.5, 0.0, 1.0, 1.0, 1.0)
            else:
                shape = AABB(0.0, 0.0, 0.0, 1.0, 0.5, 1.0)
            return BlockStateDefinition(name, (shape,), props)
        if block_type == "minecraft:trapdoor":
            if str(properties.get("open", "false")) == "true":
                return BlockStateDefinition(name, (), props)
            top = str(properties.get("half", "bottom")) == "top"
            y0, y1 = (0.8125, 1.0) if top else (0.0, 0.1875)
            return BlockStateDefinition(name, (AABB(0.0, y0, 0.0, 1.0, y1, 1.0),), props)
        if block_type == "minecraft:door":
            if (
                str(properties.get("half", "lower")) == "upper"
                or str(properties.get("open", "false")) == "true"
            ):
                return BlockStateDefinition(name, (), props)
            return BlockStateDefinition(name, (AABB(0.0, 0.0, 0.0, 1.0, 2.0, 0.1875),), props)
        if block_type in {
            "minecraft:button",
            "minecraft:lever",
            "minecraft:torch",
            "minecraft:wall_torch",
            "minecraft:flower",
            "minecraft:sapling",
            "minecraft:rail",
            "minecraft:powered_rail",
            "minecraft:detector_rail",
            "minecraft:activator_rail",
            "minecraft:redstone_wire",
            "minecraft:vine",
            "minecraft:seagrass",
            "minecraft:tall_flower",
        }:
            return BlockStateDefinition(name, (), props)
        if block_type in {
            "minecraft:fence",
            "minecraft:wall",
            "minecraft:iron_bars",
            "minecraft:stained_glass_pane",
        }:
            # A post plus connections is a stable approximation and prevents
            # the common "walk through a fence" error without overblocking.
            shapes = [AABB(0.375, 0.0, 0.375, 0.625, 1.5, 0.625)]
            for direction, key in (
                ("north", "north"),
                ("south", "south"),
                ("west", "west"),
                ("east", "east"),
            ):
                if str(properties.get(key, "false")) == "true":
                    if direction == "north":
                        shapes.append(AABB(0.375, 0.0, 0.0, 0.625, 1.5, 0.5))
                    elif direction == "south":
                        shapes.append(AABB(0.375, 0.0, 0.5, 0.625, 1.5, 1.0))
                    elif direction == "west":
                        shapes.append(AABB(0.0, 0.0, 0.375, 0.5, 1.5, 0.625))
                    else:
                        shapes.append(AABB(0.5, 0.0, 0.375, 1.0, 1.5, 0.625))
            return BlockStateDefinition(name, tuple(shapes), props)
        if block_type in {"minecraft:flower_pot", "minecraft:lantern", "minecraft:candle"}:
            return BlockStateDefinition(name, (AABB(0.2, 0.0, 0.2, 0.8, 0.6, 0.8),), props)
        if block_type == "minecraft:pressure_plate":
            return BlockStateDefinition(
                name,
                (AABB(0.0625, 0.0, 0.0625, 0.9375, 0.0625, 0.9375),),
                props,
            )
        if block_type == "minecraft:stair":
            # The lower half is represented by two boxes; orientation-specific
            # corner boxes can be installed by callers for exact replay.
            half = str(properties.get("half", "bottom")) == "top"
            if half:
                shapes = (AABB(0.0, 0.5, 0.0, 1.0, 1.0, 1.0), AABB(0.0, 0.0, 0.0, 0.5, 0.5, 1.0))
            else:
                shapes = (AABB(0.0, 0.0, 0.0, 1.0, 0.5, 1.0), AABB(0.5, 0.5, 0.0, 1.0, 1.0, 1.0))
            return BlockStateDefinition(name, shapes, props)
        return BlockStateDefinition(name, full, props)


@dataclass(frozen=True, slots=True)
class PalettedContainer:
    values: tuple[int, ...]
    bits_per_entry: int = 0
    palette_size: int | None = 1
    storage_long_count: int = 0

    def get(self, index: int) -> int:
        return self.values[index]

    @classmethod
    def decode(
        cls,
        reader: PacketReader,
        *,
        entry_count: int,
        min_indirect_bits: int = 1,
        max_indirect_bits: int,
        max_direct_bits: int,
        fixed_storage: bool = False,
    ) -> PalettedContainer:
        bits = reader.read_unsigned_byte()
        if bits > max_direct_bits:
            raise ProtocolError(f"palette uses unsupported {bits} bits per entry")
        palette: list[int] | None
        if bits == 0:
            palette = [reader.read_varint()]
            storage_bits = 0
        elif bits <= max_indirect_bits:
            storage_bits = max(bits, min_indirect_bits)
            palette_length = reader.read_varint()
            if palette_length <= 0 or palette_length > 1 << storage_bits:
                raise ProtocolError(f"invalid palette length {palette_length} for {bits} bits")
            palette = [reader.read_varint() for _ in range(palette_length)]
        else:
            palette = None
            # PaletteProvider.Dynamic stores direct/global IDs at the full
            # registry width, even if a peer supplied a smaller wire value.
            storage_bits = max_direct_bits

        if bits == 0:
            if not fixed_storage:
                long_count = reader.read_varint()
                if long_count != 0:
                    raise ProtocolError("single-valued palette must not contain packed data")
            return cls((palette[0],) * entry_count, 0, 1, 0)

        values_per_long = 64 // storage_bits
        required_longs = math.ceil(entry_count / values_per_long)
        long_count = required_longs if fixed_storage else reader.read_varint()
        if not 0 <= long_count <= entry_count or long_count != required_longs:
            raise ProtocolError(
                f"palette needs {required_longs} longs for {entry_count} entries, got {long_count}"
            )
        packed = [reader.read_unsigned_long() for _ in range(long_count)]
        mask = (1 << storage_bits) - 1
        values: list[int] = []
        for index in range(entry_count):
            packed_long = packed[index // values_per_long]
            packed_value = (
                packed_long >> ((index % values_per_long) * storage_bits)
            ) & mask
            if palette is not None:
                if packed_value >= len(palette):
                    raise ProtocolError("packed palette index is outside palette")
                packed_value = palette[packed_value]
            values.append(packed_value)
        return cls(
            tuple(values),
            storage_bits,
            len(palette) if palette is not None else None,
            long_count,
        )


@dataclass(frozen=True, slots=True)
class ChunkSection:
    non_air_count: int
    fluid_count: int
    blocks: PalettedContainer
    biomes: PalettedContainer

    @classmethod
    def decode(cls, reader: PacketReader, *, protocol: int) -> ChunkSection:
        non_air_count = reader.read_short()
        # 26.1 split the old combined counter into independent block and
        # fluid shorts.  In 1.21.11 a waterlogged block can still contribute
        # twice to the single wire count, so only protocol 774 permits 8192.
        max_non_air_count = 4096 if protocol >= 775 else 8192
        if not 0 <= non_air_count <= max_non_air_count:
            raise ProtocolError(f"invalid non-air block count {non_air_count}")
        fluid_count = reader.read_short() if protocol >= 775 else 0
        if not 0 <= fluid_count <= 4096:
            raise ProtocolError(f"invalid fluid count {fluid_count}")
        blocks = PalettedContainer.decode(
            reader,
            entry_count=4096,
            min_indirect_bits=4,
            max_indirect_bits=8,
            max_direct_bits=15,
            # 1.21.11 introduced PacketByteBuf.readFixedLengthLongArray for
            # paletted chunk containers.  Every supported protocol therefore
            # omits the VarInt long-array length; deriving this from 26.2 only
            # misaligns the first non-singleton section on protocols 774/775.
            fixed_storage=protocol >= 774,
        )
        biomes = PalettedContainer.decode(
            reader,
            entry_count=64,
            min_indirect_bits=1,
            max_indirect_bits=3,
            max_direct_bits=7,
            fixed_storage=protocol >= 774,
        )
        return cls(non_air_count, fluid_count, blocks, biomes)


@dataclass(slots=True)
class Chunk:
    x: int
    z: int
    min_y: int
    sections: list[ChunkSection]

    def get_state_id(self, x: int, y: int, z: int) -> int:
        section_index = (y - self.min_y) // 16
        if not 0 <= section_index < len(self.sections):
            return 0
        local_y = (y - self.min_y) & 15
        index = (local_y << 8) | ((z & 15) << 4) | (x & 15)
        return self.sections[section_index].blocks.get(index)

    def set_state_id(self, x: int, y: int, z: int, state_id: int) -> None:
        section_index = (y - self.min_y) // 16
        if not 0 <= section_index < len(self.sections):
            return
        local_y = (y - self.min_y) & 15
        index = (local_y << 8) | ((z & 15) << 4) | (x & 15)
        section = self.sections[section_index]
        values = list(section.blocks.values)
        values[index] = state_id
        self.sections[section_index] = ChunkSection(
            section.non_air_count,
            section.fluid_count,
            PalettedContainer(
                tuple(values),
                section.blocks.bits_per_entry,
                section.blocks.palette_size,
                section.blocks.storage_long_count,
            ),
            section.biomes,
        )


class World:
    def __init__(
        self,
        block_states: BlockStateRegistry | None = None,
        *,
        protocol: int = 776,
        release: str | None = None,
    ) -> None:
        self.protocol = protocol
        self.release = release
        self.min_y = -64
        self.height = 384
        self.block_states = block_states or BlockStateRegistry()
        # Protocol 775 is shared by three releases whose registry tables must
        # never be guessed from the protocol number alone. Bot supplies its
        # exact release; standalone World users can do the same explicitly.
        bundled_release = release or {774: "1.21.11", 776: "26.2"}.get(protocol)
        if block_states is None and bundled_release is not None:
            builtin = (
                Path(__file__).with_name("data")
                / f"blocks-{bundled_release}.json.gz"
            )
            if builtin.exists():
                self.block_states.load_table(builtin)
        self.chunks: dict[tuple[int, int], Chunk] = {}
        self._entity_collision_provider: Callable[[AABB], list[AABB]] | None = None

    def set_entity_collision_provider(
        self,
        provider: Callable[[AABB], list[AABB]] | None,
    ) -> None:
        self._entity_collision_provider = provider

    def entity_collision_boxes(self, query: AABB) -> list[AABB]:
        if self._entity_collision_provider is None:
            return []
        return self._entity_collision_provider(query)

    @property
    def max_y(self) -> int:
        """Exclusive upper world bound, matching vanilla dimension height."""

        return self.min_y + self.height

    def set_dimension_bounds(self, min_y: int, height: int) -> None:
        if height <= 0 or height % 16:
            raise ValueError("dimension height must be a positive multiple of 16")
        self.min_y = min_y
        self.height = height

    def load_chunk(self, chunk_x: int, chunk_z: int, data: bytes) -> Chunk:
        reader = PacketReader(data)
        sections: list[ChunkSection] = []
        decoded_spans: list[str] = []
        for section_index in range(self.height // 16):
            offset = reader.offset
            try:
                section = ChunkSection.decode(reader, protocol=self.protocol)
                sections.append(section)
                decoded_spans.append(
                    f"{section_index}@{offset}:{reader.offset} "
                    f"blocks={section.blocks.bits_per_entry}/{section.blocks.storage_long_count} "
                    f"biomes={section.biomes.bits_per_entry}/{section.biomes.storage_long_count}"
                )
            except ProtocolError as error:
                recent = "; ".join(decoded_spans[-3:]) or "none"
                context = data[max(0, offset - 24) : min(len(data), offset + 24)].hex()
                raise ProtocolError(
                    f"chunk ({chunk_x}, {chunk_z}) section {section_index} "
                    f"at byte {offset}: {error}; previous sections: {recent}; "
                    f"nearby bytes: {context}"
                ) from error
        reader.expect_end()
        chunk = Chunk(chunk_x, chunk_z, self.min_y, sections)
        self.chunks[(chunk_x, chunk_z)] = chunk
        return chunk

    def unload_chunk(self, chunk_x: int, chunk_z: int) -> None:
        self.chunks.pop((chunk_x, chunk_z), None)

    def get_state_id(self, x: int, y: int, z: int) -> int:
        chunk = self.chunks.get((x >> 4, z >> 4))
        return 0 if chunk is None else chunk.get_state_id(x, y, z)

    def set_state_id(self, x: int, y: int, z: int, state_id: int) -> None:
        chunk = self.chunks.get((x >> 4, z >> 4))
        if chunk is not None:
            chunk.set_state_id(x, y, z, state_id)

    def block_properties(self, x: int, y: int, z: int) -> BlockProperties:
        return self.block_states.get(self.get_state_id(x, y, z)).properties

    def fluid_height(self, x: int, y: int, z: int) -> float:
        return fluid_height(self, x, y, z)

    def fluid_flow(self, x: int, y: int, z: int) -> Vec3:
        return fluid_flow(self, x, y, z)

    def collision_boxes(self, query: AABB) -> list[AABB]:
        result: list[AABB] = []
        for x in range(math.floor(query.min_x), math.floor(query.max_x) + 1):
            for y in range(math.floor(query.min_y), math.floor(query.max_y) + 1):
                for z in range(math.floor(query.min_z), math.floor(query.max_z) + 1):
                    definition = self.block_states.get(self.get_state_id(x, y, z))
                    for shape in definition.shapes:
                        world_shape = shape.move(x, y, z)
                        if world_shape.intersects(query):
                            result.append(world_shape)
        return result

    def block_collision_boxes(self, x: int, y: int, z: int) -> tuple[AABB, ...]:
        definition = self.block_states.get(self.get_state_id(x, y, z))
        return tuple(shape.move(x, y, z) for shape in definition.shapes)

    def no_collision(self, query: AABB) -> bool:
        return not self.collision_boxes(query) and not self.entity_collision_boxes(query)
